### ISSUE TITLE
Project files browser progress

### ISSUE THREAD

**Issue by thomsong** [scrowl-io/authoring#139]
Old/inaccurate dialog shows when adding new files.

1) No Files in project
2) Added val resume
3) Clicked add new file
4) Dialog shows with old data and 2/2 (not sure where the 2 came from)

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/999242/206216929-6783fe59-eb5d-42fd-b047-0ef7984b15c2.png">

**Comment by aubeOSG** [comment]
Since we are converting images on upload/import there are now two steps involved: transformation to `.webp`, then coping to the location.

The first step (1/2) always displays a progress bar of 50% as the lib being used does not have progress events.

The second step (2/2) is moving the optimized image to the save location. This does give out progress (which you can see in the dev tools console logs), but the files are typically quite small and the move happens so quickly that you don't see the progress bar grow.

**Comment by aubeOSG** [comment]
@thomsong does the comment above resolve this issue?

**Comment by thomsong** [comment]
It explains the 1/2 and 2/2, but it doesn't explain why it shows up again with old info when you select a second file to add.
